version: '3.5'

services:
  mp-api-mongo:
    container_name: soft-rank-mongo-db
    image: mongo:4.4
    restart: always
    volumes:
      - ./docker/mongo/data:/data/db
    ports:
      - 27017:27017
